name: Auto-approve dependabot PRs
on: pull_request

jobs:
  auto-approve-prs:
    runs-on: ubuntu-latest
    steps:
      - name: auto approve dependabot pull requests
        uses: hmarr/auto-approve-action@v2.0.0
        if:
          github.actor == 'dependabot[bot]' || github.actor ==
          'dependabot-preview[bot]'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
